import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])

In [7]:
np.sum((a,b),axis=1)

array([ 6, 15])

# Find N Largest number from numpy array
# [12,43,2,100,54,5,68] ==> 100 , 68

In [9]:
x = np.array([12,43,2,100,54,5,68])

In [12]:
x

array([ 12,  43,   2, 100,  54,   5,  68])

In [10]:
temp = np.argsort(x)

In [14]:
temp

array([2, 5, 0, 1, 4, 6, 3])

In [16]:
x[temp[-2:]]

array([ 68, 100])

x[temp[-2:][::-1]]

# Replace odd in an array with -1

In [25]:
a = np.arange(0,10)
b=a
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
index = 0
for x in a:
    if x % 2 == 1:
        a[index]=-1
        
    index+=1

In [21]:
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [27]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
b[b%2==1]=-1

In [29]:
b

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [1]:
lista=[1,2,65,7,8,25]

In [8]:
print(lista.sort())
lista

None


[1, 2, 7, 8, 25, 65]